name = "Ground Zero"
author = "mxxntype"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd450213b135bc52ec95d9c79cfb049309d5a2f6cc3be49eb227cec4a33f31df"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
