name = "Ground Zero"
author = "mxxntype"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6bc97b8174fd2cbe47919ef771f9bcc4920d3fb940d48954b64a30c553ce184"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
