name = "Ground Zero"
author = "mxxntype"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36f69766d293a6ab11f76b015bf2b9911af7759a531ff0fcb92c49078c8b45da"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
