name = "Ground Zero"
author = "mxxntype"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3a5f83efc566254431924c7a7192cd7a8b9e97fd8c19eb80fb793098c7535b7"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
